version: "3.9"

services:

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./Backend:/app   # optional (dev ke liye useful)
    command: ["node", "server.js"]

  frontend:
    build: ./Frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
