apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: erp-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: prasadhire/erp-backend:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/erp
